version: '3'
services:
    nginx:
        build:
            context: ./app/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./app/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app
        depends_on:
            - postgres
            - mailer
    php-cli:
        build:
            context: ./app/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
            - composer:/root/.composer/cache
        depends_on:
            - postgres
            - mailer
    node:
          image: node:15.6-alpine
          volumes:
              - ./app:/app
          working_dir: /app
    postgres:
        image: postgres:13.1-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
    storage-public:
        build:
            context: ./storage/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./storage:/app
        ports:
            - "8081:80"
    storage-ftp:
        image: stilliard/pure-ftpd
        environment:
            FTP_USER_NAME: app
            FTP_USER_PASS: secret
            FTP_USER_HOME: /app
        volumes:
            - ./storage/public:/app
volumes:
    composer:
    postgres:
