doctrine:
    dbal:

        driver: 'pdo_pgsql'
        server_version: '13.1'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: ~

        url: '%env(resolve:DATABASE_URL)%'

        types:
            user_id: 'App\Model\User\Entity\IdType'
            user_email: 'App\Model\User\Entity\EmailType'
            user_role: 'App\Model\User\Entity\RoleType'
            font_id: 'App\Model\Font\Entity\IdType'
            font_status: 'App\Model\Font\Entity\StatusType'
            font_license: 'App\Model\Font\Entity\LicenseType'
            font_languages: 'App\Model\Font\Entity\LanguageType'
            font_face_id: 'App\Model\Font\Entity\Face\IdType'
            font_file_id: 'App\Model\Font\Entity\File\IdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Font:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Font/Entity'
                prefix: 'App\Model\Font\Entity'
                alias: Font
